name: Build and Push Docker Image to docker hub

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      #  Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mycrawler:latest \
                          -t ${{ secrets.DOCKER_USERNAME }}/mycrawler:${{ github.sha }} .

      # Docker 이미지 푸시
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,windows/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mycrawler:latest
            ${{ secrets.DOCKER_USERNAME }}/mycrawler:${{ github.sha }}